CREATE TABLE works.humans
(human_id
                     BIGINT UNIQUE NOT NULL PRIMARY KEY
     GENERATED BY DEFAULT AS IDENTITY ,
 human_first_name VARCHAR(40)NOT NULL,
 human_last_name VARCHAR(40)NOT NULL ,
 human_date_of_birth DATE NOT NULL ,
 human_phone_number VARCHAR(20) NOT NULL,
 human_email VARCHAR(50) UNIQUE ,
 human_address BIGINT ,
human_resister_date timestamp default now(),
FOREIGN KEY (human_address) REFERENCES works.addresses(address_id) );