CREATE TYPE  employee_status AS enum (
    'WORKING',
    'FIRED',
    'VACATION',
    'SICK_LEAVE');
CREATE TABLE works.employees
(employee_id
                     BIGINT UNIQUE NOT NULL PRIMARY KEY
     GENERATED BY DEFAULT  AS IDENTITY ,
     employee_date_of_employment DATE,
     employee_education VARCHAR(40) NOT NULL ,
     employee_department BIGINT,
 employee_status employee_status default 'WORKING') ;

