CREATE TABLE public.museums
(
    museum_id                BIGINT UNIQUE NOT NULL PRIMARY KEY
       generated by default as identity ,
    museum_name              VARCHAR(40) UNIQUE ,
    museum_registration_date timestamp DEFAULT now(),
    museum_address           BIGINT,
    museum_email             VARCHAR(40),
    museum_phone             VARCHAR(20)
);
ALTER TABLE museums add constraint museum_address_fk
    foreign key (museum_address) REFERENCES public.addresses(address_id);

