CREATE TABLE public.excursions
(
    excursion_id            BIGINT UNIQUE NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY ,
    excursion_name          VARCHAR(40),
    excursion_guide         VARCHAR(30) NOT NULL,
    excursion_start         timestamp ,
    excursion_and           timestamp ,
    excursion_register_date timestamp default NOW()
);