CREATE TABLE public .lectures
(
    lecture_id            BIGINT UNIQUE NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY ,
    lecture_name          VARCHAR(40),
    lecture_description   VARCHAR(40),
    lecture_lecturer      BIGINT,
    lecture_start         timestamp ,
    lecture_and           timestamp ,
    lecture_excursion   BIGINT ,
    lecture_register_date timestamp default NOW(),

    FOREIGN KEY (lecture_lecturer) REFERENCES public.employees (employee_id),
    FOREIGN KEY (lecture_excursion)REFERENCES public.excursions(excursion_id)

);